name: my_ml_env
channels:
- conda-forge
dependencies:
- python=3.12.7
- pip<=25.1
- pip:
  - mlflow==2.18.0
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - psutil==5.9.0
  - scikit-learn==1.3.2
  - scipy==1.13.1
  - gunicorn